version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    working_directory: ~/lychee
    steps:
      - checkout
      - run: |
          bundle install
          bundle exec rspec spec
